### ISSUE TITLE
NOT AN ISSUE:::: 

### ISSUE THREAD

**Issue by ctkqiang** [VISWESWARAN1998/CyberGod-KSGMPRH#3]
It is good concept you made. Ever consider a Mac or UNIX version ?  :)

**Comment by VISWESWARAN1998** [comment]
Yes, the new version is going to be based on Yara so it will be cross-platformed.

**Comment by VISWESWARAN1998** [comment]
@johnmelodyme The wait is over:

New project does it all: https://github.com/VISWESWARAN1998/Mrida
